#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LemoFire <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt> 
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/LemoFire/autoOpenWrt>
#

name: ðŸŒ…masterpw

on:
  push:
    branches: 
      - master

jobs:

  build_openwrt:

    name: æ ‘èŽ“æ´¾4B

    runs-on: ubuntu-latest

    steps:
      - name: ç©ºé—´æ¸…ç†å’Œåˆå§‹åŒ–çŽ¯å¢ƒ
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: æ ¡éªŒæœ¬åœ°æ–‡ä»¶
        uses: actions/checkout@main

      - name: å…‹éš†æºç 
        run: |
          git clone -b master --single-branch https://github.com/openwrt/openwrt
          mv ./openwrt/* ./

      - name: æ›´æ–°feedsæº
        run: |
          ./scripts/feeds update -a

      - name: åˆ é™¤éƒ¨åˆ†packagesæ–‡ä»¶
        run: |
          pushd feeds/packages/net
          rm -rf adguardhome
          rm -rf dnsproxy
          rm -rf microsocks
          rm -rf smartdns
          rm -rf trojan-go
          rm -rf v2ray-core
          rm -rf v2ray-geodata
          rm -rf xray-core

      - name: åˆ é™¤éƒ¨åˆ†luciæ–‡ä»¶
        run: |
          pushd feeds/luci/applications
          rm -rf luci-app-adguardhome
          rm -rf luci-app-pbr

      - name: å®‰è£…feedsæº
        run: |
          ./scripts/feeds install -a

      - name: æž„å»ºè‡ªå®šä¹‰æ–‡ä»¶ç»“æž„
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/symonlee/luci-app-adguardhome
          git clone https://github.com/symonlee/openwrt-smartdns xipk
          svn co https://github.com/Lienol/openwrt-package/branches/other/lean/ipv6-helper
          git clone https://github.com/xiaorouji/openwrt-passwall
          git clone -b luci --single-branch https://github.com/xiaorouji/openwrt-passwall luci-app-passwall
          pushd luci-app-passwall/luci-app-passwall/root/etc
          rm -rf hotplug.d

      - name: è½½å…¥è‡ªå®šä¹‰é…ç½®
        run: |
          sed -i "s/timezone='.*'/timezone='HKT-8'/g" package/base-files/files/bin/config_generate
          sed -i "/.*ttylogin='0'.*/i\                                set system.@system[-1].zonename='Asia/Hong Kong'" package/base-files/files/bin/config_generate
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF

          # ç¼–è¯‘rpi-4å›ºä»¶:
          CONFIG_TARGET_bcm27xx=y
          CONFIG_TARGET_bcm27xx_bcm2711=y
          CONFIG_TARGET_bcm27xx_bcm2711_DEVICE_rpi-4=y

          # ç¼–è¯‘ext4å›ºä»¶:
          CONFIG_TARGET_ROOTFS_EXT4FS=y
          # CONFIG_TARGET_ROOTFS_SQUASHFS is not set

          # è®¾ç½®å›ºä»¶å¤§å°:
          CONFIG_TARGET_ROOTFS_PARTSIZE=1984

          # IPv6æ”¯æŒ:
          # CONFIG_PACKAGE_dnsmasq is not set
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ip6tables-mod-nat=y
          CONFIG_PACKAGE_ipv6helper=y

          # æ–‡ä»¶ç³»ç»Ÿæ”¯æŒ:
          CONFIG_PACKAGE_block-mount=y

          # åŽ»æŽ‰æ¿è½½æ— çº¿:
          # CONFIG_PACKAGE_cypress-firmware-43455-sdio is not set
          # CONFIG_PACKAGE_cypress-nvram-43455-sdio-rpi-4b is not set
          # CONFIG_PACKAGE_kmod-brcmfmac is not set

          # USB3.0æ”¯æŒ:
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y

          # ç³»ç»Ÿä¸­æ–‡æ”¯æŒ:
          CONFIG_LUCI_LANG_zh_Hans=y

          # å¸¸ç”¨LuCIæ’ä»¶é€‰æ‹©:
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_PACKAGE_luci-app-ksmbd=y
          CONFIG_PACKAGE_luci-app-opkg=y
          CONFIG_PACKAGE_luci-app-passwall=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Geodata=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set
          CONFIG_PACKAGE_luci-app-sqm=y

          # å¸¸ç”¨è½¯ä»¶åŒ…:
          CONFIG_PACKAGE_AdGuardHome=y
          CONFIG_PACKAGE_ca-certificates=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_dnsproxy=y
          CONFIG_PACKAGE_fdisk=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_kmod-tcp-bbr=y
          # CONFIG_PACKAGE_wpad-basic-wolfssl is not set
          # CONFIG_XRAY_CORE_COMPRESS_UPX is not set
          
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: ä¸‹è½½è½¯ä»¶åŒ…
        run: make download -j16

      - name: è¿›è¡Œå›ºä»¶ç¼–è¯‘
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: å›ºä»¶æ•´ç†
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Upload buildinfo
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
